### ISSUE TITLE
Confusion with handlebars+jquery integration

### ISSUE THREAD

**Issue by connorrowland** [connorrowland/forum#1]
@awongh @WilliamfShaw @DBrodsky90 
Hey guys,
I've been working on a feature that will allow a user to click on a box and see it expand to a larger box. I'd like to instruct handlebars to add certain text to the large box that will not be in the small box, but I'm not sure how to do so. Right now, my "posts" file creates a div for each post. Each of these divs has the a class of "small-box". When a user clicks on the box, the class changes to "large-box." I want to be able to know which specific box was clicked, because right now when a user clicks any box, it changes the class of all small boxes to "large-box." Here's my posts.handlebars file and the app.js that sets a click event: 

![screen shot 2015-07-21 at 10 30 22 am](https://cloud.githubusercontent.com/assets/11824142/8803191/88370d84-2f93-11e5-839d-951d2b9e8615.png)

Thanks
-Connor

**Comment by WilliamfShaw** [comment]
.small-box may not exist on page load, you may need to delagte the click event. Look into delegated click events.

**Comment by connorrowland** [comment]
That worked!!!!! Tanx Will
